package appconst

const ERROR_OK = 0
const ERROR_AUTH_FAIL = 1
const ERROR_CONNECT_MYSQL_FAIL = 2
const ERROR_PROXY_LISTEN_FAIL = 3
const ERROR_PROXY_ACCEPT_FAIL = 4

//sql -前缀10 认证相关
const ERROR_MUST_SECURE_CONNECTION = 1001
const ERROR_READ_CLIENT_RESPONSE = 1002
const ERROR_WRITE_INITIAL_PACKET = 1003
const ERROR_CLIENT_USERANME_WRONG = 1004
const ERROR_CLIENT_PASSWORD_WRONG = 1005

//sql -前缀11 查询相关
const ERROR_COMMAND_WRITE_ERROR = 1005
